version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            PKG_VERSION=$(cat ./package.json | grep version | cut -d '"' -f4)
            if [[ "${CIRCLE_TAG}" != "v${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${CIRCLE_TAG}"
              echo "  PKG_VERSION: v${PKG_VERSION}"
              exit 1
            fi
      - run:
          name: Build S3 Lambda
          command: |
            npm ci --production
            zip logdna-s3.zip -r node_modules/ index.js package-lock.json lib/*.js
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-s3.zip
  approve:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - ./logdna-s3.zip
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: .
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: Create a Release
          command: |
            ghr \
              -n "LogDNA S3 Lambda Function ${CIRCLE_TAG}" \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -draft ${CIRCLE_TAG} ./logdna-s3.zip
workflows:
  update:
    jobs:
      - test:
          filters: *tagged_build_filters
      - build:
          requires:
            - test
          filters: *tagged_build_filters
      - approve:
          type: approval
          requires:
            - build
          filters: *tagged_build_filters
      - release:
          requires:
            - approve
          filters: *tagged_build_filters
  test:
    jobs:
      - test:
          filters: *test_build_filters
